/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package git_20056001_munozcarreno;

/**
 *
 * @author CLundstedt
 */
public class PrincipalWindow extends javax.swing.JFrame {
    private Repositorio repositorio;
    private GitController gitController;
    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow(Repositorio repositorio,GitController gitController) {
        initComponents();
        this.repositorio = repositorio;
        this.gitController = gitController;
        this.setLocationRelativeTo(null);
        this.TF_NameZome.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BTN_Workspace = new javax.swing.JButton();
        BTN_Local = new javax.swing.JButton();
        BTN_Remote = new javax.swing.JButton();
        BTN_Index = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BTN_add = new javax.swing.JButton();
        BTN_commit = new javax.swing.JButton();
        BTN_push = new javax.swing.JButton();
        BTN_pull = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_InfoZones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        TF_NameZome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repositorio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Workspace");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Index");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Remote Repository");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Local Repository");

        BTN_Workspace.setText("Status Workspace");
        BTN_Workspace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_Workspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickWActionPerformed(evt);
            }
        });

        BTN_Local.setText("Status Local");
        BTN_Local.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_Local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickLActionPerformed(evt);
            }
        });

        BTN_Remote.setText("Status Remote");
        BTN_Remote.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_Remote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickRActionPerformed(evt);
            }
        });

        BTN_Index.setText("Status Index");
        BTN_Index.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_Index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickIActionPerformed(evt);
            }
        });

        jButton5.setText("Nuevo Archivo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickNewFileActionPerformed(evt);
            }
        });

        BTN_add.setText("add");
        BTN_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventAddActionPerformed(evt);
            }
        });

        BTN_commit.setText("commit");
        BTN_commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventCommitActionPerformed(evt);
            }
        });

        BTN_push.setText("push");
        BTN_push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventPushActionPerformed(evt);
            }
        });

        BTN_pull.setText("pull");
        BTN_pull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventPullActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        jLabel5.setText("Comandos disponibles:");

        TA_InfoZones.setColumns(20);
        TA_InfoZones.setRows(5);
        TA_InfoZones.setEnabled(false);
        jScrollPane1.setViewportView(TA_InfoZones);

        jLabel6.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        jLabel6.setText("Información de las zonas de trabajo:");

        jLabel7.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel7.setText("Git");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TF_NameZome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TF_NameZome.setForeground(new java.awt.Color(128, 128, 128));
        TF_NameZome.setBorder(null);
        TF_NameZome.setCaretColor(new java.awt.Color(128, 128, 128));
        TF_NameZome.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_pull, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_push, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_commit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TF_NameZome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_Workspace, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(BTN_Index, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(BTN_Local, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Remote, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Workspace, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Index, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Local, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Remote, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_add)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_commit)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_push)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_pull)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(TF_NameZome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EVENTOS RELACIONADOS CON LOS ESTADOS DE LAS ZONAS DE TRABAJO
    
    
    private void EventClickWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickWActionPerformed
        // AQUI SE PROCEDE A MOSTRAR LA INFORMACIÓN DE LA ZONA WORKSPACE
        this.TF_NameZome.setText("Workspace");
        this.TF_NameZome.setBorder(null);
        this.TA_InfoZones.setText(null);
        String StatusW = gitController.gitStatusWorkspace(repositorio);
        this.TA_InfoZones.setText(StatusW);
    }//GEN-LAST:event_EventClickWActionPerformed

    private void EventClickIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickIActionPerformed
        // AQUI SE PROCEDE A MOSTRAR LA INFORMACIÓN DE LA ZONA INDEX
        // AQUI SE PROCEDE A MOSTRAR LA INFORMACIÓN DE LA ZONA WORKSPACE
        this.TF_NameZome.setText("Index");
        this.TF_NameZome.setBorder(null);
        this.TA_InfoZones.setText(null);
        String StatusI = gitController.gitStatusIndex(repositorio);
        this.TA_InfoZones.setText(StatusI);
        
    }//GEN-LAST:event_EventClickIActionPerformed

    private void EventClickLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventClickLActionPerformed

    private void EventClickRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventClickRActionPerformed

    
    //EVENTOS RELACIONADOS CON LA ENTRADA DE DATOS
    
    
    private void EventClickNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickNewFileActionPerformed
        //se debe abrir una ventana temporal para ingresar nombre de autor y archivo
        //SE CREA UN OBJETO DE TIPO WindowNewFile
        this.TA_InfoZones.setText(null);
        if(repositorio == null){
            System.out.printf("EL REPOSITORIO ES NULL AWEONAOOOO.\n");
        }
        WindowNewFile WindowForCreateFile = new WindowNewFile(repositorio,gitController);
        //LA CENTANA SE HACE VISIBLE PARA EL USUARIO
        WindowForCreateFile.setVisible(true);
        //this.dispose();
        this.setVisible(false);
        
        
    }//GEN-LAST:event_EventClickNewFileActionPerformed

    private void EventAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventAddActionPerformed
        // No es necesario abrir ninguna ventana
        //solo hace falta modificar el repotorio y algun mensaje de informacion
        
        // se vacia el text area de informacion de zonas de trabajo
        this.TA_InfoZones.setText(null);
        WindowHowSendFiles Windowcapa1 = new WindowHowSendFiles(repositorio,gitController);
        Windowcapa1.setVisible(true);
        this.setVisible(false);
        
        /*
        PrincipalWindow KeepWindow3 = new PrincipalWindow(gitController.gitAdd(repositorio.getZonas(), repositorio),gitController);
        KeepWindow3.setVisible(true);
        this.setVisible(false);
        
        */
        
        
        
    }//GEN-LAST:event_EventAddActionPerformed

    private void EventCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventCommitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventCommitActionPerformed

    private void EventPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventPushActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventPushActionPerformed

    private void EventPullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventPullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventPullActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Index;
    private javax.swing.JButton BTN_Local;
    private javax.swing.JButton BTN_Remote;
    private javax.swing.JButton BTN_Workspace;
    private javax.swing.JButton BTN_add;
    private javax.swing.JButton BTN_commit;
    private javax.swing.JButton BTN_pull;
    private javax.swing.JButton BTN_push;
    private javax.swing.JTextArea TA_InfoZones;
    private javax.swing.JTextField TF_NameZome;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
