/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package git_20056001_munozcarreno;

/**
 *
 * @author CLundstedt
 */
public class WindowTranferFilesCap2 extends javax.swing.JFrame {

    private Repositorio repositorio;
    private GitController gitController;
    private int AmountFiles;
    /**
     * Creates new form WindowTranferFilesCap2
     */
    public WindowTranferFilesCap2(Repositorio repositorio,GitController gitController, int AmountFiles) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.repositorio = repositorio;
        this.gitController = gitController;
        this.AmountFiles = AmountFiles;
        //se pasa el entero AmountFiles como String 
        String Cadena = String.valueOf(AmountFiles);
        this.TF_ShowAmountFiles.setText(Cadena);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_ShowAmountFiles = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_FilesAvailables = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        TF_PutNumberFile = new javax.swing.JTextField();
        BTN_TransferFiles = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencia de archivos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Archivos por enviar:");

        TF_ShowAmountFiles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TF_ShowAmountFiles.setForeground(new java.awt.Color(128, 128, 128));
        TF_ShowAmountFiles.setBorder(null);
        TF_ShowAmountFiles.setCaretColor(new java.awt.Color(128, 128, 128));
        TF_ShowAmountFiles.setEnabled(false);
        TF_ShowAmountFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventShowAmountFilesActionPerformed(evt);
            }
        });

        TA_FilesAvailables.setColumns(20);
        TA_FilesAvailables.setRows(5);
        TA_FilesAvailables.setEnabled(false);
        TA_FilesAvailables.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                EventShowFilesAvailablesActionPerformed(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TA_FilesAvailables);

        jLabel2.setText("N° archivo:");

        TF_PutNumberFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickPutNumberFileActionPerformed(evt);
            }
        });

        BTN_TransferFiles.setText("Transferir");
        BTN_TransferFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickTransferFilesActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivos disponibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_ShowAmountFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TF_PutNumberFile, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(BTN_TransferFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_ShowAmountFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_TransferFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_PutNumberFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventShowAmountFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventShowAmountFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventShowAmountFilesActionPerformed

    private void EventShowFilesAvailablesActionPerformed(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_EventShowFilesAvailablesActionPerformed
        // Se muestran los archivos disponibles en workspace
        this.TA_FilesAvailables.setText(gitController.gitFilesToTransfer(repositorio));
    }//GEN-LAST:event_EventShowFilesAvailablesActionPerformed

    private void EventClickPutNumberFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickPutNumberFileActionPerformed
        
        
    }//GEN-LAST:event_EventClickPutNumberFileActionPerformed

    private void EventClickTransferFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickTransferFilesActionPerformed
        // Aqui se procede a tranferir el archivo a la zona index, la ventana
        //se vuelve a reaparecer hasta que todos los archivos sean
        //transferidos
        
        // se obtiene el numero ingresado por el usuario
        String NumberChoose = this.TF_PutNumberFile.getText();
        
        
        
    }//GEN-LAST:event_EventClickTransferFilesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_TransferFiles;
    private javax.swing.JTextArea TA_FilesAvailables;
    private javax.swing.JTextField TF_PutNumberFile;
    private javax.swing.JTextField TF_ShowAmountFiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
