/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package git_20056001_munozcarreno;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author CLundstedt
 */
public class WindowNewFile extends javax.swing.JFrame {

    private Repositorio repositorio;
    private GitController gitController;
    private ArrayList<String> COMANDOS;
    //JFrame parentWindow;
    /**
     * Creates new form WindowNewFile
     */
    public WindowNewFile(Repositorio repositorio,GitController gitController,ArrayList<String> COMANDOS) {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.parentWindow = parentWindow;
        this.repositorio=repositorio;
        this.gitController = gitController;
        this.COMANDOS = COMANDOS;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_ImputNameFileCreateFileActionPerformed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_ImputContenidoCreateFileActionPerformed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BTN_SendDatasCreateFileActionPerformed = new javax.swing.JButton();
        BTN_ApplyNameFileCreateFile = new javax.swing.JButton();
        BTN_ApplyContentCreateFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo archivo");

        jLabel1.setText("Nombre archivo:");

        TF_ImputNameFileCreateFileActionPerformed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_ImputNameFileCreateFileKeyTyped(evt);
            }
        });

        jLabel2.setText("Contenido de archivo:");

        TF_ImputContenidoCreateFileActionPerformed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_ImputContenidoCreateFileKeyTyped(evt);
            }
        });

        jLabel3.setText("Ingrese los datos solicitados para ingresar un nuevo archivo:");

        BTN_SendDatasCreateFileActionPerformed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTN_SendDatasCreateFileActionPerformed.setText("Enviar datos");
        BTN_SendDatasCreateFileActionPerformed.setBorder(new javax.swing.border.MatteBorder(null));
        BTN_SendDatasCreateFileActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickSendDatasCreateFileActionPerformed(evt);
            }
        });

        BTN_ApplyNameFileCreateFile.setText("Aplicar");
        BTN_ApplyNameFileCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickSendNameFileCreateFile(evt);
            }
        });

        BTN_ApplyContentCreateFile.setText("Aplicar");
        BTN_ApplyContentCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventClickSendContentCreateFile(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_ImputContenidoCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_ImputNameFileCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_ApplyNameFileCreateFile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_ApplyContentCreateFile, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_SendDatasCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_ImputNameFileCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ApplyNameFileCreateFile))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_ImputContenidoCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ApplyContentCreateFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(BTN_SendDatasCreateFileActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventClickSendDatasCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickSendDatasCreateFileActionPerformed
         //SE ANALIZA LA ENTRADA DEL NOMBRE DEL ARCHIVO Y EL CONTENIDO DE ESTE
         String NameFile = this.TF_ImputNameFileCreateFileActionPerformed.getText();
         String Content = this.TF_ImputContenidoCreateFileActionPerformed.getText();

         try{
          
         
            PrincipalWindow KeepWindow2 = new PrincipalWindow(gitController.gitAgregarArchivo(NameFile, Content,repositorio.getZonas(),repositorio),gitController,COMANDOS);
            KeepWindow2.setVisible(true);
            this.setVisible(false);
  
         }
         catch(DatasCreateFileInvalidException e){
             JOptionPane.showMessageDialog(this, "Por favor, rellene los recuadros indicados", "Error de datos", JOptionPane.ERROR_MESSAGE);
             
         }
        
        
   
    }//GEN-LAST:event_EventClickSendDatasCreateFileActionPerformed

    private void EventClickSendNameFileCreateFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickSendNameFileCreateFile
      
        System.out.printf("Click en aceptar nombre de autor.\n");
        String NameFile = this.TF_ImputNameFileCreateFileActionPerformed.getText();
        if(NameFile == null || NameFile.isEmpty() || NameFile.trim().isEmpty()){
            System.out.printf("Error en entrada de nombre de autor.\n");
            this.TF_ImputNameFileCreateFileActionPerformed.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        else{
          System.out.printf("Entrada valida de nombre de autor.\n");  
          this.TF_ImputNameFileCreateFileActionPerformed.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_EventClickSendNameFileCreateFile
         
    private void EventClickSendContentCreateFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventClickSendContentCreateFile
        // TODO add your handling code here:
        System.out.printf("Click en aceptar contenido del archivo.\n");
        String Content = this.TF_ImputContenidoCreateFileActionPerformed.getText();
        if(Content == null || Content.isEmpty() || Content.trim().isEmpty()){
            System.out.printf("Error en entrada contenido de archivo.\n");
            this.TF_ImputContenidoCreateFileActionPerformed.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        else{
          System.out.printf("Entrada valida de nombre de autor.\n");  
          this.TF_ImputContenidoCreateFileActionPerformed.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_EventClickSendContentCreateFile

    private void TF_ImputContenidoCreateFileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_ImputContenidoCreateFileKeyTyped
        // TODO add your handling code here:
        String Content = this.TF_ImputContenidoCreateFileActionPerformed.getText();
        if(Content != null && !Content.isEmpty() && !Content.trim().isEmpty()){
            System.out.printf("volver a borde original.\n");
            this.TF_ImputContenidoCreateFileActionPerformed.setBorder(BorderFactory.createLoweredSoftBevelBorder());
        }
    }//GEN-LAST:event_TF_ImputContenidoCreateFileKeyTyped

    private void TF_ImputNameFileCreateFileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_ImputNameFileCreateFileKeyTyped
        // TODO add your handling code here:
        String NameFile = this.TF_ImputNameFileCreateFileActionPerformed.getText();
        if(NameFile != null && !NameFile.isEmpty() && !NameFile.trim().isEmpty()){
            System.out.printf("volver a borde original.\n");
            this.TF_ImputNameFileCreateFileActionPerformed.setBorder(BorderFactory.createLoweredSoftBevelBorder());
        }
    }//GEN-LAST:event_TF_ImputNameFileCreateFileKeyTyped

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ApplyContentCreateFile;
    private javax.swing.JButton BTN_ApplyNameFileCreateFile;
    private javax.swing.JButton BTN_SendDatasCreateFileActionPerformed;
    private javax.swing.JTextField TF_ImputContenidoCreateFileActionPerformed;
    private javax.swing.JTextField TF_ImputNameFileCreateFileActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
