/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.GitController;
import Modelo.Repositorio;
import java.util.ArrayList;

/**
 *
 * @author CLundstedt
 */
public class WindowFor5Commits extends javax.swing.JFrame {

    private Repositorio repositorio;
    private GitController gitController;
    private ArrayList<String> COMANDOS;
    /**
     * Creates new form WindowFor5Commits
     */
    public WindowFor5Commits(Repositorio repositorio, GitController gitController, ArrayList<String> COMANDOS) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.repositorio = repositorio;
        this.gitController = gitController;
        this.COMANDOS = COMANDOS;   
        
        
        //AQUI SE DEBE MOSTRAR LOS ULTIMOS 5 COMMITS
        //SE ACTUALIZA EL TEXT AREA
        this.TA_LastFiveCommits.setText(gitController.gitLog(repositorio.getZonas()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA_LastFiveCommits = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Últimos 5 commit de Local Repository");

        TA_LastFiveCommits.setColumns(20);
        TA_LastFiveCommits.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TA_LastFiveCommits.setRows(5);
        TA_LastFiveCommits.setEnabled(false);
        jScrollPane1.setViewportView(TA_LastFiveCommits);

        jButton1.setText("Volver al menú principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventReturnPrincipalWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * EVENTO VINCULADO AL BOTON "Volver al menú principal", SE RETORNA A LA VENTANA PRINCIPAL
     * @param evt 
     */
    private void EventReturnPrincipalWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventReturnPrincipalWindowActionPerformed
        // se vuelve a PrincipalWindow
        PrincipalWindow ReturnWindow = new PrincipalWindow(repositorio,gitController,COMANDOS);
        ReturnWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EventReturnPrincipalWindowActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA_LastFiveCommits;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
